#!/bin/bash
base1=/home/srinibasn/dftfe_xcGPU/ctestGPU/testsGPU/pseudopotential/real
base2=/home/srinibasn/dftfe_xcGPU/ctestGPU/testsGPU/pseudopotential/real/accuracyBenchmarks
for file in $base1/output*; do
    filename=$(basename "$file")
    tmp1="./${filename}.tmp1"
    tmp2="./${filename}.tmp2"
    grep -v -e '^Found' -e '^MPI' "$file" > "$tmp1"
    grep -v -e '^Found' -e '^MPI' "$base2/$filename" > "$tmp2"
    diff -u -U0 -P "$tmp1" "$tmp2" > "${filename}.diff"
    # Add vim diff command at the top with full paths
    sed -i "1ivimdiff $file $base2/$filename" "${filename}.diff"
    rm "$tmp1" "$tmp2"
    if [ ! -s "${filename}.diff" ]; then
        rm "${filename}.diff"
    else
        echo "${filename}"
    fi
    done